(()=>{'use strict';
const mode=document.body.dataset.mode,svg=document.querySelector('#circuit'),partsLayer=document.querySelector('#parts'),wiresLayer=document.querySelector('#wires'),previewLayer=document.querySelector('#wirePreview'),$=id=>document.getElementById(id),ns='http://www.w3.org/2000/svg';
const analogTypes={VSIN:{name:'Fonte senoidal',pins:['+','−'],amp:5,freq:60,offset:0},VDC:{name:'Fonte DC',pins:['+','−'],voltage:5},R:{name:'Resistor',pins:['1','2'],resistance:1000},C:{name:'Capacitor',pins:['1','2'],capacitance:100e-6},D:{name:'Diodo de silício',pins:['A','K']},GND:{name:'Terra',pins:['GND']},PROBE:{name:'Ponta do osciloscópio',pins:['V']}};
const digitalTypes={SW:{name:'Chave lógica',pins:['Y'],value:0},AND:{name:'AND · 7408',pins:['A','B','Y']},OR:{name:'OR · 7432',pins:['A','B','Y']},NOT:{name:'NOT · 7404',pins:['A','Y']},NAND:{name:'NAND · 7400',pins:['A','B','Y']},NOR:{name:'NOR · 7402',pins:['A','B','Y']},XOR:{name:'XOR · 7486',pins:['A','B','Y']},LOGIC0:{name:'Entrada constante 0',pins:['Y'],value:0},LOGIC1:{name:'Entrada constante 1',pins:['Y'],value:1},XNOR:{name:'XNOR',pins:['A','B','Y']},LED:{name:'LED de saída',pins:['A']}};
const library=mode==='analog'?analogTypes:digitalTypes;let circuit={mode,components:[],wires:[],nextId:1,frequency:60},selected=null,drag=null,wireStart=null,simData=[],digitalState={values:new Map(),root:k=>k};let dirHandle=null;
const palette=$('palette');for(const [type,meta]of Object.entries(library)){const b=document.createElement('button');b.className='part';b.draggable=true;b.innerHTML=`<b>${type==='VSIN'?'V~':type==='VDC'?'V⎓':type==='GND'?'⏚':type==='PROBE'?'CH':type==='SW'?'SW':type==='LED'?'LED':type}</b><small>${meta.name}</small>`;b.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',type));b.addEventListener('click',()=>{const i=circuit.components.length;addPart(type,220+(i%5)*180,100+(Math.floor(i/5)%3)*150)});palette.append(b)}
function sEl(tag,attrs={},txt){const e=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(txt!==undefined)e.textContent=txt;return e}
function meta(p){return library[p.type]}function pinLocal(p,i){if(p.type==='LOGIC0'||p.type==='LOGIC1')return[108,29];if(p.type==='GND')return[54,5];if(p.type==='PROBE')return[0,29];if(p.type==='SW')return[108,29];if(p.type==='LED')return[0,29];if(p.type==='NOT')return i===0?[0,29]:[118,29];if(meta(p).pins.length===3)return i===0?[0,16]:i===1?[0,42]:p.type==='NOR'||p.type==='XNOR'?[126,29]:p.type==='NAND'?[118,29]:[108,29];return i===0?[0,29]:[108,29]}
function pinKey(id,i){return `${id}:${i}`}function absolutePin(p,i){const [x,y]=pinLocal(p,i);return{x:p.x+x,y:p.y+y}}
function body(p){if(p.type==='D'||p.type==='GND'||p.type==='PROBE'||p.type==='C')return sEl('g',{});if(p.type==='LOGIC0'||p.type==='LOGIC1')return sEl('circle',{class:'component-body constant-source',cx:54,cy:29,r:17});if(['VSIN','VDC'].includes(p.type))return sEl('circle',{class:'component-body',cx:54,cy:29,r:22});if(p.type==='R')return sEl('g',{});if(p.type==='LED')return sEl('path',{class:`component-body lamp-body ${p.level===1?'on':'off'}`,d:'M54 3C40 3 29 14 29 29c0 10 7 17 15 23l3 4h14l3-4c8-6 15-13 15-23C79 14 68 3 54 3Z'});if(p.type==='SW')return sEl('g',{});if(p.type==='NOT')return sEl('path',{class:'component-body',d:'M20 8L82 29L20 50Z'});if(['AND','NAND'].includes(p.type))return sEl('path',{class:'component-body',d:'M12 5H48A24 24 0 0 1 48 53H12Z'});if(['OR','NOR','XOR','XNOR'].includes(p.type))return sEl('path',{class:'component-body',d:'M12 5Q38 29 12 53Q48 53 96 29Q48 5 12 5Z'});return sEl('rect',{class:'component-body',x:12,y:5,width:84,height:48,rx:18})}
function drawPart(p){const g=sEl('g',{class:`component${selected===p.id?' selected':''}`,transform:`translate(${p.x} ${p.y})`,'data-id':p.id,'data-type':p.type});if(p.type==='LED'&&p.level===1)g.append(sEl('circle',{class:'lamp-glow',cx:54,cy:27,r:29}));const b=body(p);g.append(b);if(p.type==='LOGIC0'||p.type==='LOGIC1'){g.append(sEl('path',{class:'component-lead',d:'M69 29H108'}));g.append(sEl('text',{x:54,y:35,'text-anchor':'middle',class:'constant-value'},String(p.value)))}if(p.type==='SW'){g.append(sEl('path',{class:'component-lead',d:'M82 29H108'}));g.append(sEl('circle',{class:'switch-contact',cx:34,cy:29,r:3}));g.append(sEl('circle',{class:'switch-contact',cx:82,cy:29,r:3}));g.append(sEl('path',{class:`switch-lever ${p.value?'on':'off'}`,d:p.value?'M36 29H80':'M36 29L69 14'}))}if(p.type==='LED'){g.append(sEl('path',{class:'component-lead',d:'M0 29H29'}));g.append(sEl('path',{class:'lamp-base',d:'M46 55H62M48 58H60'}));g.append(sEl('path',{class:`lamp-filament ${p.level===1?'on':'off'}`,d:'M46 42Q54 31 62 42M46 42V48M62 42V48'}))}if(p.type==='NOT'){g.append(sEl('path',{class:'component-lead',d:'M0 29H20 M92 29H118'}));g.append(sEl('circle',{class:'inversion-bubble',cx:88,cy:29,r:4}))}if(['AND','NAND'].includes(p.type))g.append(sEl('path',{class:'component-lead',d:'M0 16H12 M0 42H12 M72 29H93 M103 29H118'}));if(['OR','NOR','XOR','XNOR'].includes(p.type))g.append(sEl('path',{class:'component-lead',d:'M0 16H17 M0 42H17 M96 29H101 M111 29H126'}));if(p.type==='R')g.append(sEl('path',{d:'M0 29H20l7-12 10 24 10-24 10 24 10-24 10 24 7-12h24',stroke:'#e8f0f4','stroke-width':3,fill:'none','stroke-linejoin':'round'}));if(p.type==='NPN')g.append(sEl('path',{d:'M0 29H42m0-17v34m0-29 27-13h39m-39 0L58 21m-16 16h16m0 0 27 14h15m-42-14 11 3-5-10',stroke:'#e8f0f4','stroke-width':3,fill:'none','stroke-linecap':'round','stroke-linejoin':'round'}));if(p.type==='VSIN')g.append(sEl('path',{d:'M39 29c5-15 10-15 15 0s10 15 15 0',stroke:'#e8f0f4','stroke-width':2.5,fill:'none'}));if(p.type==='VDC')g.append(sEl('path',{d:'M54 15v9m-4-5h8m-4 13v9',stroke:'#e8f0f4','stroke-width':2}));if(p.type==='D'){g.append(sEl('path',{d:'M30 29h20m0-13v26m0-26 24 13-24 13m24-26v26m0-13h20',stroke:'#d8e8ee','stroke-width':3,fill:'none'}))}else if(p.type==='C'){g.append(sEl('path',{d:'M0 29h43m0-15v30m12-30v30m0-15h53',stroke:'#d8e8ee','stroke-width':3,fill:'none'}))}else if(p.type==='GND'){g.append(sEl('path',{d:'M54 5v12m-16 0h32m-26 6h20m-14 6h8',stroke:'#d8e8ee','stroke-width':2,fill:'none'}))}else if(p.type==='PROBE'){g.append(sEl('path',{d:'M5 42L48 29',stroke:'#d8e8ee','stroke-width':2,fill:'none'}));g.append(sEl('circle',{cx:54,cy:29,r:5,fill:'#4bd7e8'}))}else if(p.type==='SW'||p.type==='LED'){}else if(p.type==='C')g.append(sEl('text',{x:54,y:62,'text-anchor':'middle',class:'sym'},'C'));else if(p.type==='D')g.append(sEl('text',{x:54,y:62,'text-anchor':'middle',class:'sym'},'D'));
const gatePart=['AND','OR','NOT','NAND','NOR','XOR','XNOR'].includes(p.type);g.append(sEl('text',{x:54,y:gatePart?-5:p.type==='C'||p.type==='D'?78:67,'text-anchor':'middle',class:'ref'},p.name||`${p.type}${p.id}`));if(['NAND','NOR','XNOR'].includes(p.type))g.append(sEl('circle',{class:'inversion-bubble',cx:p.type==='NOR'||p.type==='XNOR'?106:98,cy:29,r:4}));if(p.type==='XOR'||p.type==='XNOR')g.append(sEl('path',{d:'M5 5Q31 29 5 53',stroke:'#5a8999','stroke-width':2,fill:'none'}));const val=p.type==='R'?fmt(p.resistance,'Ω'):p.type==='C'?fmt(p.capacitance,'F'):p.type==='VSIN'?`${fmt(p.amp,'V')} · ${fmt(p.freq,'Hz')}`:p.type==='VDC'?fmt(p.voltage,'V'):p.type==='SW'?String(p.value):'';if(val)g.append(sEl('text',{x:54,y:p.type==='C'||p.type==='D'?92:82,'text-anchor':'middle',class:'value'},val));meta(p).pins.forEach((pin,i)=>{const [x,y]=pinLocal(p,i),c=sEl('circle',{class:'pin','data-pin':pinKey(p.id,i),cx:x,cy:y,r:mode==='digital'?2.7:6});const title=sEl('title',{},pin);c.append(title);g.append(c)});g.addEventListener('pointerdown',e=>{if(e.target.classList.contains('pin'))return;drag={id:p.id,start:point(e),origX:p.x,origY:p.y,moved:false};e.preventDefault();e.stopPropagation()});g.addEventListener('click',e=>{if(e.target.classList.contains('pin'))return;if(p.type==='SW'){p.value=p.value?0:1;update();selected=p.id;renderInspector();return}selected=p.id;draw();renderInspector()});partsLayer.append(g)}
function fmt(n,u){if(!Number.isFinite(+n))return '?';if(u==='Ω')return +n>=1e6?(+n/1e6).toPrecision(3)+' MΩ':+n>=1e3?(+n/1e3).toPrecision(3)+' kΩ':(+n).toPrecision(3)+' Ω';if(u==='F')return +n>=1e-3?(+n*1e3).toPrecision(3)+' mF':+n>=1e-6?(+n*1e6).toPrecision(3)+' µF':(+n*1e9).toPrecision(3)+' nF';if(u==='Hz')return +n>=1e3?(+n/1e3).toPrecision(3)+' kHz':(+n).toPrecision(3)+' Hz';return (+n).toPrecision(3)+' '+u}
function point(e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(svg.getScreenCTM().inverse());return{x:q.x,y:q.y}}
function addPart(type,x,y){const p={...library[type],id:circuit.nextId++,type,x:Math.max(30,Math.round(x/20)*20),y:Math.max(35,Math.round(y/20)*20),name:`${type}${circuit.nextId-1}`};circuit.components.push(p);selected=p.id;draw();renderInspector();update();$('runStatus').textContent=`${p.name} adicionado. Arraste seus terminais para ligar.`}
function drawWire(w){const a=findPin(w.a),b=findPin(w.b);if(!a||!b)return;const mid=(a.x+b.x)/2;const path=sEl('path',{class:`wire${w.high?' logic-high':''}${selected===w.id?' selected':''}`,d:`M${a.x} ${a.y} H${mid} V${b.y} H${b.x}`,'data-wire':w.id});path.addEventListener('click',e=>{e.stopPropagation();selected=w.id;renderInspector();draw()});wiresLayer.append(path)}function findPin(key){const[id,i]=key.split(':').map(Number),p=circuit.components.find(x=>x.id===id);return p?absolutePin(p,i):null}
function draw(){partsLayer.replaceChildren();wiresLayer.replaceChildren();circuit.wires.forEach(drawWire);circuit.components.forEach(drawPart);updateProbeChoices()}
function renderInspector(){const host=$('properties'),p=circuit.components.find(x=>x.id===selected);host.replaceChildren();if(!p){$('selectionHint').textContent=typeof selected==='string'?'Ligação selecionada · Delete para remover':'Folha de montagem';return} $('selectionHint').textContent=`Selecionado: ${p.name}`;const title=document.createElement('p');title.textContent=`${p.name} · ${meta(p).name}`;host.append(title);field(host,'Referência',p.name,'text',v=>{p.name=v;draw()});const props=p.type==='VSIN'?[['amp','Amplitude (V pico)','number',.1],['freq','Frequência (Hz)','number',.1],['offset','Offset DC (V)','number',.1]]:p.type==='VDC'?[['voltage','Tensão (V)','number',.1]]:p.type==='R'?[['resistance','Resistência (Ω)','number',1]]:p.type==='C'?[['capacitance','Capacitância (F)','number',1e-9]]:p.type==='SW'?[['value','Nível lógico','toggle']]:[];for(const [key,label,type,step]of props)field(host,label,p[key],type,v=>{p[key]=type==='number'?+v:v;draw()},step);if(mode==='digital'&&['AND','OR','NOT','NAND','NOR','XOR','XNOR'].includes(p.type)){const msg=document.createElement('p');msg.textContent='Saída e entradas aparecem na simulação ao conectar os terminais.';host.append(msg)}const del=document.createElement('button');del.className='delete-part';del.textContent='Excluir componente';del.onclick=()=>removePart(p.id);host.append(del)}
function field(host,label,value,type,change,step){const l=document.createElement('label');l.textContent=label;if(type==='toggle'){const b=document.createElement('button');b.textContent=`${value?'1 · HIGH':'0 · LOW'}  (alternar)`;b.onclick=()=>{change(value?0:1);update();renderInspector()};l.append(b)}else{const i=document.createElement('input');i.type=type;i.value=value;i.step=step||'any';i.addEventListener('change',()=>change(i.value));l.append(i)}host.append(l)}
function removePart(id){circuit.components=circuit.components.filter(p=>p.id!==id);circuit.wires=circuit.wires.filter(w=>!w.a.startsWith(id+':')&&!w.b.startsWith(id+':'));selected=null;draw();renderInspector()}
svg.addEventListener('dragover',e=>{e.preventDefault();svg.classList.add('drop-active')});svg.addEventListener('dragleave',()=>svg.classList.remove('drop-active'));svg.addEventListener('drop',e=>{e.preventDefault();svg.classList.remove('drop-active');const q=point(e);addPart(e.dataTransfer.getData('text/plain'),q.x-54,q.y-29)});
svg.addEventListener('pointerdown',e=>{const pin=e.target.closest?.('.pin');if(pin){wireStart=pin.dataset.pin;const q=point(e);previewLayer.replaceChildren(sEl('path',{class:'wire-preview',d:`M${q.x} ${q.y}L${q.x} ${q.y}`}));e.preventDefault();return}if(e.target===svg||e.target.tagName==='rect'){selected=null;renderInspector()}});
svg.addEventListener('pointermove',e=>{if(drag){const q=point(e),dx=q.x-drag.start.x,dy=q.y-drag.start.y;if(Math.hypot(dx,dy)>3)drag.moved=true;if(drag.moved){const p=circuit.components.find(x=>x.id===drag.id);p.x=Math.max(10,drag.origX+dx);p.y=Math.max(10,drag.origY+dy);const g=partsLayer.querySelector(`[data-id="${p.id}"]`);g?.setAttribute('transform',`translate(${p.x} ${p.y})`);wiresLayer.replaceChildren();circuit.wires.forEach(drawWire)}}if(wireStart){const a=findPin(wireStart),q=point(e);previewLayer.replaceChildren(sEl('path',{class:'wire-preview',d:`M${a.x} ${a.y} H${(a.x+q.x)/2} V${q.y} H${q.x}`}))}});
svg.addEventListener('pointerup',e=>{if(drag){const moved=drag.moved,p=circuit.components.find(x=>x.id===drag.id);drag=null;if(moved){p.x=Math.round(p.x/20)*20;p.y=Math.round(p.y/20)*20;selected=p.id;draw();renderInspector()}return}if(wireStart){const pin=e.target.closest?.('.pin'),end=pin?.dataset.pin;if(end&&end!==wireStart&&!circuit.wires.some(w=>(w.a===wireStart&&w.b===end)||(w.b===wireStart&&w.a===end))){circuit.wires.push({id:'w'+Date.now()+Math.random().toString(16).slice(2),a:wireStart,b:end});selected=null;draw();update();$('runStatus').textContent='Ligação criada.'}else $('runStatus').textContent='Solte o fio sobre outro terminal.';wireStart=null;previewLayer.replaceChildren()}});
window.addEventListener('keydown',e=>{if((e.key==='Delete'||e.key==='Backspace')&&selected){if(typeof selected==='number')removePart(selected);else{circuit.wires=circuit.wires.filter(w=>w.id!==selected);selected=null;draw();renderInspector()}}});
function updateProbeChoices(){if(mode!=='analog')return;for(const [id,key]of[['probe1','probe1'],['probe2','probe2']]){const sel=$(id),old=sel.value;sel.replaceChildren();const empty=document.createElement('option');empty.value='';empty.textContent=id==='probe1'?'Escolha uma ponta':'Desligado';sel.append(empty);circuit.components.filter(p=>p.type==='PROBE').forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;sel.append(o)});if([...sel.options].some(o=>o.value===old))sel.value=old} }

// Build electrical nets from pin-to-pin wires. Passive parts remain circuit elements.
function nets(){const keys=[];for(const p of circuit.components)meta(p).pins.forEach((_,i)=>keys.push(pinKey(p.id,i)));const parent=new Map(keys.map(k=>[k,k]));const root=x=>{let r=x;while(parent.get(r)!==r)r=parent.get(r);while(parent.get(x)!==x){const n=parent.get(x);parent.set(x,r);x=n}return r};for(const w of circuit.wires){if(parent.has(w.a)&&parent.has(w.b))parent.set(root(w.b),root(w.a))}const ground=circuit.components.find(p=>p.type==='GND');return{parent,root,ground:ground?root(pinKey(ground.id,0)):null,node:k=>root(k)}}
function solveLinear(A,b){const n=b.length;for(let i=0;i<n;i++){let p=i;for(let r=i+1;r<n;r++)if(Math.abs(A[r][i])>Math.abs(A[p][i]))p=r;if(Math.abs(A[p][i])<1e-14)A[p][i]+=1e-10;if(p!==i){[A[p],A[i]]=[A[i],A[p]];[b[p],b[i]]=[b[i],b[p]]}const d=A[i][i];if(Math.abs(d)<1e-18)continue;for(let j=i;j<n;j++)A[i][j]/=d;b[i]/=d;for(let r=0;r<n;r++){if(r===i)continue;const f=A[r][i];if(!f)continue;for(let j=i;j<n;j++)A[r][j]-=f*A[i][j];b[r]-=f*b[i]}}return b}
function simulateAnalog(){const network=nets(),nodeKeys=[...new Set([...network.parent.keys()].map(network.root))].filter(k=>k!==network.ground),ix=new Map(nodeKeys.map((k,i)=>[k,i])),sources=circuit.components.filter(p=>p.type==='VSIN'||p.type==='VDC'),dt=1/(Math.max(1,...circuit.components.filter(p=>p.type==='VSIN').map(p=>+p.freq||60))*100),steps=200;let prev=new Map(),rows=[];const nodeOf=(p,i)=>network.root(pinKey(p.id,i));function voltage(map,p,i){const n=nodeOf(p,i);return n===network.ground?0:(map.get(n)||0)}for(let t=0;t<steps;t++){const time=t*dt;let guess=new Map();for(let iter=0;iter<5;iter++){const n=nodeKeys.length+sources.length,A=Array.from({length:n},()=>Array(n).fill(0)),b=Array(n).fill(0);const stampG=(u,v,g)=>{const i=ix.get(u),j=ix.get(v);if(i!==undefined)A[i][i]+=g;if(j!==undefined)A[j][j]+=g;if(i!==undefined&&j!==undefined){A[i][j]-=g;A[j][i]-=g}},stampI=(u,v,i)=>{const a=ix.get(u),c=ix.get(v);if(a!==undefined)b[a]-=i;if(c!==undefined)b[c]+=i},gnd=network.ground;for(let i=0;i<nodeKeys.length;i++)A[i][i]+=1e-12;
for(const p of circuit.components){if(['R','C','D'].includes(p.type)){const u=nodeOf(p,0),v=nodeOf(p,1);if(p.type==='R'){const g=1/Math.max(1e-6,+p.resistance||1000);stampG(u,v,g)}else if(p.type==='C'){const g=Math.max(1e-12,+p.capacitance||1e-6)/dt;stampG(u,v,g);const old=(prev.get(u)||0)-(prev.get(v)||0);stampI(u,v,-g*old)}else{const forward=voltage(guess,p,0)-voltage(guess,p,1)>.65;if(forward){const g=10;stampG(u,v,g);stampI(u,v,-g*.65)}}}}
sources.forEach((p,k)=>{const u=nodeOf(p,0),v=nodeOf(p,1),i=nodeKeys.length+k,iu=ix.get(u),iv=ix.get(v);if(iu!==undefined){A[iu][i]+=1;A[i][iu]+=1}if(iv!==undefined){A[iv][i]-=1;A[i][iv]-=1}const value=p.type==='VSIN'?(+p.offset||0)+(+p.amp||5)*Math.sin(2*Math.PI*(+p.freq||60)*time):(+p.voltage||5);b[i]=value});const x=solveLinear(A,b),next=new Map(nodeKeys.map((k,i)=>[k,x[i]]));guess=next}
prev=guess;const out={time};for(const p of circuit.components.filter(p=>p.type==='PROBE'))out[p.id]=voltage(guess,p,0);rows.push(out)}simData=rows;drawScope();$('runStatus').textContent=`Simulação concluída: ${steps} passos · modelo transitório didático.`}
function drawScope(){if(mode!=='analog')return;const c=$('scope'),ctx=c.getContext('2d'),W=c.width,H=c.height;ctx.clearRect(0,0,W,H);ctx.strokeStyle='#244337';for(let i=0;i<=8;i++){const x=20+(W-40)*i/8;ctx.beginPath();ctx.moveTo(x,10);ctx.lineTo(x,H-18);ctx.stroke()}for(let i=0;i<=6;i++){const y=10+(H-28)*i/6;ctx.beginPath();ctx.moveTo(20,y);ctx.lineTo(W-20,y);ctx.stroke()}const ids=[$('probe1').value,$('probe2').value].filter(Boolean),colors=['#f3ce62','#4bd7e8'];let peak=0;for(const id of ids)for(const row of simData)peak=Math.max(peak,Math.abs(row[id]||0));const scale=peak||1,mid=(H-10)/2;ids.forEach((id,k)=>{ctx.strokeStyle=colors[k];ctx.lineWidth=2;ctx.beginPath();simData.forEach((r,i)=>{const x=20+i/(Math.max(1,simData.length-1))*(W-40),y=mid-(r[id]||0)/scale*(H-38)/2;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()});$('readings').innerHTML=ids.map((id,k)=>{const vals=simData.map(r=>r[id]||0);return `<span class="reading" style="color:${colors[k]}">${circuit.components.find(p=>String(p.id)===id)?.name||'CH'}: <b>${(Math.max(...vals)-Math.min(...vals)).toFixed(3)} Vpp</b></span>`}).join('')||'<span class="reading">Adicione pontas de osciloscópio e escolha os canais.</span>'}
function simulateDigital(){const n=nets(),values=new Map(),net=k=>n.root(k);for(const p of circuit.components.filter(p=>['SW','LOGIC0','LOGIC1'].includes(p.type)))values.set(net(pinKey(p.id,0)),p.type==='LOGIC1'?1:p.type==='LOGIC0'?0:(+p.value||0));for(let pass=0;pass<circuit.components.length+1;pass++){let changed=false;for(const p of circuit.components.filter(p=>['AND','OR','NOT','NAND','NOR','XOR','XNOR'].includes(p.type))){const a=values.get(net(pinKey(p.id,0))),b=p.type==='NOT'?0:values.get(net(pinKey(p.id,1)));if(a===undefined||(p.type!=='NOT'&&b===undefined))continue;let y=p.type==='AND'?a&b:p.type==='OR'?a|b:p.type==='NOT'?1-a:p.type==='NAND'?1-(a&b):p.type==='NOR'?1-(a|b):p.type==='XOR'?a^b:1-(a^b);const out=net(pinKey(p.id,meta(p).pins.length-1));if(values.get(out)!==y){values.set(out,y);changed=true}}if(!changed)break}digitalState={values,root:net};for(const p of circuit.components.filter(p=>p.type==='LED'))p.level=values.get(net(pinKey(p.id,0)));for(const w of circuit.wires)w.high=values.get(net(w.a))===1;draw();const switches=circuit.components.filter(p=>p.type==='SW'),gates=circuit.components.filter(p=>['AND','OR','NOT','NAND','NOR','XOR','XNOR'].includes(p.type));let html='<p>Saídas dos LEDs:</p>';const leds=circuit.components.filter(p=>p.type==='LED');html+=leds.length?`<ul>${leds.map(p=>`<li>${p.name}: <b class="${p.level===1?'led-on':''}">${p.level===undefined?'flutuando':p.level?'1 · aceso':'0 · apagado'}</b></li>`).join('')}</ul>`:'<p>Adicione um LED e conecte sua entrada a uma saída.</p>';if(switches.length&&gates.length){html+='<p>Entradas atuais: '+switches.map(p=>`${p.name}=${p.value}`).join(' · ')+'</p>'} $('digitalResult').innerHTML=html;$('runStatus').textContent='Simulação lógica concluída.'}
function digitalValue(part,pin){return digitalState.values.get(digitalState.root(pinKey(part.id,pin)))}
function update(){if(mode==='analog')simulateAnalog();else simulateDigital()}

const report3Specs=[
 {file:'01_INVERSOR_NAND_A0_LED1.png',kind:'inverter',a:0,expected:1},
 {file:'02_INVERSOR_NAND_A1_LED0.png',kind:'inverter',a:1,expected:0},
 {file:'03_AND_NAND_A0_B0_LED0.png',kind:'and',a:0,b:0,expected:0},
 {file:'04_AND_NAND_A0_B1_LED0.png',kind:'and',a:0,b:1,expected:0},
 {file:'05_AND_NAND_A1_B0_LED0.png',kind:'and',a:1,b:0,expected:0},
 {file:'06_AND_NAND_A1_B1_LED1.png',kind:'and',a:1,b:1,expected:1},
 {file:'07_OR_NAND_A0_B0_LED0.png',kind:'or',a:0,b:0,expected:0},
 {file:'08_OR_NAND_A0_B1_LED1.png',kind:'or',a:0,b:1,expected:1},
 {file:'09_OR_NAND_A1_B0_LED1.png',kind:'or',a:1,b:0,expected:1},
 {file:'10_OR_NAND_A1_B1_LED1.png',kind:'or',a:1,b:1,expected:1}
];
function buildReport3Circuit(spec){
 circuit={mode:'digital',components:[],wires:[],nextId:1,frequency:60};selected=null;
 const add=(type,x,y,name,extra={})=>{const p={...library[type],...extra,id:circuit.nextId++,type,x,y,name};circuit.components.push(p);return p};
 const sw=(name,value,x,y)=>add('SW',x,y,name,{value}),nand=(x,y)=>add('NAND',x,y,'7400'),led=(x,y)=>add('LED',x,y,'LED');
 const wire=(a,ap,b,bp)=>circuit.wires.push({id:`r3w${circuit.wires.length+1}`,a:pinKey(a.id,ap),b:pinKey(b.id,bp)});
 const join=(a,b,input)=>wire(a,a.type==='SW'?0:2,b,input),branch=(source,target)=>{join(source,target,0);join(source,target,1)};
 if(spec.kind==='inverter'){
  const a=sw('A',spec.a,85,310),n=nand(490,300),l=led(850,300);branch(a,n);join(n,l,0);
 }else if(spec.kind==='and'){
  const a=sw('A',spec.a,70,230),b=sw('B',spec.b,70,390),n1=nand(410,290),n2=nand(770,290),l=led(1060,290);
  join(a,n1,0);join(b,n1,1);branch(n1,n2);join(n2,l,0);
 }else if(spec.kind==='or'){
  const a=sw('A',spec.a,50,80),b=sw('B',spec.b,50,330),n1=nand(360,65),n2=nand(360,315),n3=nand(780,190),l=led(1080,190);
  branch(a,n1);branch(b,n2);join(n1,n3,0);join(n2,n3,1);join(n3,l,0);
 }
}
function reportSvgBlob(){
 const sourceBounds=[partsLayer.getBBox(),wiresLayer.getBBox()].filter(box=>box.width||box.height);
 if(!sourceBounds.length)throw new Error('O circuito nao contem componentes conectaveis.');
 const x0=Math.min(...sourceBounds.map(box=>box.x))-24,y0=Math.min(...sourceBounds.map(box=>box.y))-30;
 const x1=Math.max(...sourceBounds.map(box=>box.x+box.width))+24,y1=Math.max(...sourceBounds.map(box=>box.y+box.height))+36;
 const scale=Math.min(1080/Math.max(1,x1-x0),590/Math.max(1,y1-y0)),tx=600-(x0+x1)*scale/2,ty=360-(y0+y1)*scale/2;
 const imageSvg=$('circuit').cloneNode(true);imageSvg.setAttribute('xmlns',ns);imageSvg.setAttribute('width','2400');imageSvg.setAttribute('height','1440');imageSvg.setAttribute('data-mode','digital');imageSvg.removeAttribute('id');
 const copyComputed=(source,target)=>{const computed=getComputedStyle(source),properties=['fill','fill-opacity','stroke','stroke-width','stroke-linecap','stroke-linejoin','stroke-dasharray','opacity','filter','display','visibility','font-family','font-size','font-weight','text-anchor','pointer-events','shape-rendering','paint-order'];const declarations=properties.map(name=>{const value=computed.getPropertyValue(name);return value?`${name}:${value}`:''}).filter(Boolean).join(';');if(declarations)target.setAttribute('style',declarations);const a=source.children,b=target.children;for(let i=0;i<Math.min(a.length,b.length);i++)copyComputed(a[i],b[i])};
 copyComputed($('circuit'),imageSvg);const background=imageSvg.querySelector(':scope > rect:first-of-type');background?.setAttribute('fill','#f9fbfc');imageSvg.querySelector(':scope > rect:nth-of-type(2)')?.remove();
 let grid='';for(let x=0;x<=1200;x+=20)grid+=`M${x} 0V720 `;for(let y=0;y<=720;y+=20)grid+=`M0 ${y}H1200 `;const gridLines=sEl('path',{d:grid,fill:'none',stroke:'#e1e7ec','stroke-width':.7,'pointer-events':'none'});imageSvg.insertBefore(gridLines,imageSvg.querySelector('#wires'));
 const wires=imageSvg.querySelector('#wires'),parts=imageSvg.querySelector('#parts');imageSvg.querySelector('.wire-preview')?.remove();const group=sEl('g',{transform:`translate(${tx} ${ty}) scale(${scale})`});wires.parentNode.insertBefore(group,wires);group.append(wires,parts);return new Blob([new XMLSerializer().serializeToString(imageSvg)],{type:'image/svg+xml;charset=utf-8'});
}
async function renderReport3Png(){const svgBlob=reportSvgBlob(),url=URL.createObjectURL(svgBlob);try{const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(new Error('O navegador nao renderizou o SVG da montagem.'));image.src=url});const canvas=document.createElement('canvas');canvas.width=2400;canvas.height=1440;const ctx=canvas.getContext('2d');ctx.fillStyle='#fbfcfd';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);return await new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Falha ao exportar PNG.')),'image/png'))}finally{URL.revokeObjectURL(url)}}
function checkReport3(spec){const leds=circuit.components.filter(p=>p.type==='LED'),gates=circuit.components.filter(p=>['AND','OR','NOT','NAND','NOR','XOR','XNOR'].includes(p.type)),nands=gates.filter(p=>p.type==='NAND');if(leds.length!==1||leds[0].level!==spec.expected)throw new Error(`${spec.file}: LED=${leds[0]?.level??'flutuando'}; esperado ${spec.expected}.`);const count=spec.kind==='inverter'?1:spec.kind==='and'?2:3;if(gates.length!==count||nands.length!==count)throw new Error(`${spec.file}: esperadas ${count} portas NAND fisicas.`);const intermediate=nands.map(p=>digitalValue(p,2));let expected;if(spec.kind==='inverter')expected=[1-spec.a];else if(spec.kind==='and')expected=[1-(spec.a&spec.b),spec.a&spec.b];else expected=[1-spec.a,1-spec.b,spec.a|spec.b];if(intermediate.some((v,i)=>v!==expected[i]))throw new Error(`${spec.file}: saidas internas ${intermediate.join(',')} nao conferem com ${expected.join(',')}.`);return{file:spec.file,inputs:spec.kind==='inverter'?[spec.a]:[spec.a,spec.b],expected:spec.expected,led:leds[0].level,gates:gates.map(p=>p.type),gateOutputs:intermediate,wires:circuit.wires.length}}
async function generateReport3(){const button=$('generateReport3'),box=$('report3Output'),status=$('report3Status'),downloads=$('report3Downloads'),savedCircuit=JSON.parse(JSON.stringify(circuit)),savedSelection=selected;button.disabled=true;box.hidden=false;downloads.replaceChildren();status.textContent='Montando e validando 10 circuitos...';try{const built=[];for(const spec of report3Specs){buildReport3Circuit(spec);update();built.push({spec,circuit:JSON.parse(JSON.stringify(circuit)),audit:checkReport3(spec)})}const artifacts=[];for(const item of built){circuit=JSON.parse(JSON.stringify(item.circuit));selected=null;update();const audit=checkReport3(item.spec);if(audit.led!==item.audit.led)throw new Error(`${item.spec.file}: o estado mudou antes da captura.`);artifacts.push({filename:item.spec.file,blob:await renderReport3Png(),audit})}for(const artifact of artifacts){const a=document.createElement('a');a.href=URL.createObjectURL(artifact.blob);a.download=artifact.filename;a.textContent=`Baixar ${artifact.filename}`;a.dataset.filename=artifact.filename;downloads.append(a)}for(const a of downloads.querySelectorAll('a')){a.click();await new Promise(resolve=>setTimeout(resolve,180))}window.__digitalReport3Audit=artifacts.map(x=>x.audit);status.textContent='10 imagens exportadas. Se downloads automaticos forem bloqueados, use os links abaixo.'}catch(error){downloads.replaceChildren();status.textContent=`Exportacao interrompida: ${error.message}`;console.error('Report 3:',error)}finally{circuit=savedCircuit;selected=savedSelection;draw();renderInspector();button.disabled=false}}
if(mode==='digital')$('generateReport3').onclick=generateReport3;

// Local repository folder access plus portable JSON export/import.
const dbName='lab-simulator-v2',dirKey='saveDir-'+mode;function db(){return new Promise((ok,no)=>{const r=indexedDB.open(dbName,1);r.onupgradeneeded=()=>r.result.createObjectStore('handles');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}async function rememberHandle(h){dirHandle=h;const d=await db();d.transaction('handles','readwrite').objectStore('handles').put(h,dirKey)}async function recalledHandle(){try{const d=await db();return await new Promise(ok=>{const r=d.transaction('handles').objectStore('handles').get(dirKey);r.onsuccess=()=>ok(r.result||null);r.onerror=()=>ok(null)})}catch{return null}}function configuration(){return{mode,circuit}}function installConfig(data){if(data.mode!==mode||!data.circuit||!Array.isArray(data.circuit.components)){alert('Arquivo de outro simulador ou formato inválido.');return}circuit=data.circuit;selected=null;draw();renderInspector();update()}async function refreshSaved(){const box=$('savedList');box.replaceChildren();if(!dirHandle)return;try{for await(const[name,h]of dirHandle.entries()){if(!name.endsWith('.json'))continue;const row=document.createElement('span');row.className='saveditem';const open=document.createElement('button');open.textContent=name.replace(/\.json$/,'');open.onclick=async()=>{const f=await h.getFile();installConfig(JSON.parse(await f.text()))};const del=document.createElement('button');del.textContent='×';del.onclick=async()=>{await dirHandle.removeEntry(name);refreshSaved()};row.append(open,del);box.append(row)}}catch{$('saveStatus').textContent='Reconecte a pasta para abrir os circuitos.'}}
async function save(){const name=prompt('Nome do circuito:','minha-pratica');if(!name)return;const filename=name.trim().replace(/[^\p{L}\p{N}_-]+/gu,'-')+'.json',json=JSON.stringify(configuration(),null,2);if(dirHandle){try{if(await dirHandle.requestPermission({mode:'readwrite'})!=='granted')throw Error('sem permissão de escrita');const f=await dirHandle.getFileHandle(filename,{create:true}),w=await f.createWritable();await w.write(json);await w.close();$('saveStatus').textContent=`Salvo em simulador/salvos/${filename}`;refreshSaved();return}catch(e){$('saveStatus').textContent=`Não gravou na pasta (${e.message}); baixando JSON.`}}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([json],{type:'application/json'}));a.download=filename;a.click();URL.revokeObjectURL(a.href)}
$('connect').onclick=async()=>{if(!window.showDirectoryPicker){$('saveStatus').textContent='Este navegador não permite selecionar pasta; use Salvar/Abrir para trabalhar com JSON.';return}try{await rememberHandle(await showDirectoryPicker({mode:'readwrite',id:'lab-saves-'+mode}));$('saveStatus').textContent='Pasta conectada.';refreshSaved()}catch(e){if(e.name!=='AbortError')$('saveStatus').textContent=e.message}};$('save').onclick=save;$('import').onclick=()=>$('fileInput').click();$('fileInput').onchange=async e=>{const f=e.target.files[0];if(f)try{installConfig(JSON.parse(await f.text()))}catch{$('saveStatus').textContent='Arquivo JSON inválido.'}e.target.value=''};
$('newCircuit').onclick=()=>{if(circuit.components.length&&!confirm('Apagar o circuito atual e começar outro?'))return;circuit={mode,components:[],wires:[],nextId:1,frequency:60};selected=null;draw();renderInspector();$('runStatus').textContent='Folha limpa. Arraste componentes da biblioteca.'};$('deleteSelected').onclick=()=>{if(typeof selected==='number')removePart(selected);else if(selected){circuit.wires=circuit.wires.filter(w=>w.id!==selected);selected=null;draw();renderInspector()}};$('clearWires').onclick=()=>{circuit.wires=[];selected=null;draw();renderInspector()};$('run').onclick=update;if(mode==='analog'){$('probe1').onchange=drawScope;$('probe2').onchange=drawScope}
const old=recalledHandle();old.then(async h=>{if(h&&await h.queryPermission({mode:'readwrite'})==='granted'){dirHandle=h;refreshSaved()}});draw();renderInspector();
})();
